---
start_date: '2014-01-01'

listing:
    astock_listing_date: list_date
    astock_delisting_date: delist_date
    afund_listing_date: shares
    astock_list:
        table: astockstatus
        column: name

status:
    not_st: public_status_id
    tradestatus: tradestatus

trade_keys:
    returns: ret
    avgprice: avgprice
    high_limit: high_limit
    low_limit: low_limit
    
    
index_mapping:
    'star': ['002', '300', '688', '301']
    '50': '000016.XSHG'
    '000016': '000016.XSHG'
    '000016.XSHG': '000016.XSHG'
    '300': '399300.XSHE'
    '399300': '399300.XSHE'
    '399300.XSHE': '399300.XSHE'
    '500': '000905.XSHG'
    '000905': '000905.XSHG'
    '000905.XSHG': '000905.XSHG'
    '1000': '000852.XSHG'
    '000852': '000852.XSHG'
    '000852.XSHG': '000852.XSHG'
    '2000': '399303.XSHE'
    '399303': '399303.XSHE'
    '399303.XSHE': '399303.XSHE'
    'full': '399317.XSHE'
    '399317': '399317.XSHE'
    '399317.XSHE': '399317.XSHE'
---
